#!/bin/bash
echo $(( $RANDOM )) >>  $(( $RANDOM % 100 + 1)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 200 + 100)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 300 + 200)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 300 + 400)).txt
scp ./*.txt ubuntu@192.168.1.1:/home/ubuntu/
ssh ubuntu@192.168.1.1 'find /home/ubuntu/ -type f -mtime +7 -delete'
15 * * * /home/ubuntu/bash.sh
fi
