#!/bin/bash
echo $(( $RANDOM )) >>  $(( $RANDOM % 100 + 1)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 200 + 100)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 300 + 200)).txt
echo $(( $RANDOM )) >>  $(( $RANDOM % 400 + 300)).txt
scp ./*.txt azureuser@10.0.0.7:/home/azureuser/
ssh azureuser@10.0.0.7 'find /home/azureuser/ -type f -mtime +7 -delete'
1 * * * /home/azureuser/bash.sh
